name: 'Build for all platforms'

on:
  workflow_dispatch
  

jobs:

      

  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: sudo apt install openjdk-18-jdk      
      - run: wget https://dl.google.com/dl/android/studio/ide-zips/2024.1.2.12/android-studio-2024.1.2.12-linux.tar.gz
      - run: tar -zxvf android-studio-2024.1.2.12-linux.tar.gz
      - run: sudo mv android-studio /opt/
      - run: sudo ln -sf /opt/android-studio/bin/studio.sh /bin/android-studio
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter build apk
      - name: Upload apk 
        uses: actions/upload-artifact@v4
        with:
          name: otzaria-android.apk
          path: build/app/outputs/flutter-apk/app-release.apk

